Explorando o numpy

In [2]:
import numpy as np

In [3]:
lista = [1, 2, 3, 4, 5, 6]

array = np.array(lista)

In [4]:
matriz_zeros = np.zeros((5,3))
print(matriz_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
lista_notas = [9.7, 6.6, 7.5,4.3,5.75,10,3.7]
listanp_notas = np.array(lista_notas)
print(listanp_notas.mean())
print(listanp_notas.max())
print(listanp_notas.min())
print(listanp_notas.argmax())
print(listanp_notas.argmin())

6.792857142857143
10.0
3.7
5
6


Mascaras booleanas

In [13]:
is_covid_positive = np.array(['Yes','No','Yes','Yes','No','No','No','Yes'])
mask = (is_covid_positive == 'Yes')
print(mask)

[ True False  True  True False False False  True]


In [15]:
is_covid_positive[mask] = 'C19'
print(is_covid_positive)

['C19' 'No' 'C19' 'C19' 'No' 'No' 'No' 'C19']


In [27]:
grades_students = np.array([7.7,8.3,6.7,5.5,5,2.1,2.3,4.7,9.8,9.9,10,7.4,6.3])
mask_grades = (grades_students > 5)
print(mask_grades)
grades_students[mask_grades]
grades_students[grades_students <= 5]
print(grades_students[mask_grades])
print(grades_students[grades_students <= 5])


[ True  True  True  True False False False False  True  True  True  True
  True]
[ 7.7  8.3  6.7  5.5  9.8  9.9 10.   7.4  6.3]
[5.  2.1 2.3 4.7]
