Explorando o numpy

In [74]:
import numpy as np
import pandas as pd

In [75]:
lista = [1, 2, 3, 4, 5, 6]

array = np.array(lista)

In [76]:
matriz_zeros = np.zeros((5,3))
print(matriz_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [77]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [78]:
lista_notas = [9.7, 6.6, 7.5,4.3,5.75,10,3.7]
listanp_notas = np.array(lista_notas)
print(listanp_notas.mean())
print(listanp_notas.max())
print(listanp_notas.min())
print(listanp_notas.argmax())
print(listanp_notas.argmin())

6.792857142857143
10.0
3.7
5
6


Mascaras booleanas

In [79]:
is_covid_positive = np.array(['Yes','No','Yes','Yes','No','No','No','Yes'])
mask = (is_covid_positive == 'Yes')
print(mask)

[ True False  True  True False False False  True]


In [80]:
is_covid_positive[mask] = 'C19'
print(is_covid_positive)

['C19' 'No' 'C19' 'C19' 'No' 'No' 'No' 'C19']


In [81]:
grades_students = np.array([7.7,8.3,6.7,5.5,5,2.1,2.3,4.7,9.8,9.9,10,7.4,6.3])
mask_grades = (grades_students > 5)
print(mask_grades)
grades_students[mask_grades]
grades_students[grades_students <= 5]
print(grades_students[mask_grades])
print(grades_students[grades_students <= 5])


[ True  True  True  True False False False False  True  True  True  True
  True]
[ 7.7  8.3  6.7  5.5  9.8  9.9 10.   7.4  6.3]
[5.  2.1 2.3 4.7]


Pandas series e DataFrames

In [82]:
listapd = [12,23,34,45,56,67]
series_pandas = pd.Series(listapd)
print(series_pandas)

0    12
1    23
2    34
3    45
4    56
5    67
dtype: int64


In [83]:
notas = {'Lucas': 7.7,'Eduardo':9.2,'Gabriel':6.5}
serie_notas = pd.Series(notas)
print(serie_notas)
print(serie_notas.describe())

Lucas      7.7
Eduardo    9.2
Gabriel    6.5
dtype: float64
count    3.000000
mean     7.800000
std      1.352775
min      6.500000
25%      7.100000
50%      7.700000
75%      8.450000
max      9.200000
dtype: float64


In [84]:
serie_notas.sum()

np.float64(23.4)

In [85]:
dictionary = {'Autores': ['Rick Riordan', 'J. R. R. Tolkien', 'Rick Riordan', 'Machado de Assis'],
              'Titulos':['O Ladrão de Raios', 'A Sociedade do Anel', 'Mar de Monstros', 'Memórias Postumas de Brás Cubas'],
              'Preço':[41.2,35.7,39.5,40.5]}


In [86]:
df = pd.DataFrame(dictionary)

In [87]:
df

Autores                          Titulos  Preço
0      Rick Riordan                O Ladrão de Raios   41.2
1  J. R. R. Tolkien              A Sociedade do Anel   35.7
2      Rick Riordan                  Mar de Monstros   39.5
3  Machado de Assis  Memórias Postumas de Brás Cubas   40.5

In [88]:
df['Autores']

0        Rick Riordan
1    J. R. R. Tolkien
2        Rick Riordan
3    Machado de Assis
Name: Autores, dtype: object

In [89]:
df['Autores'][1]

'J. R. R. Tolkien'

In [90]:
df['Preço'].mean()

np.float64(39.225)

In [91]:
mascara = (df['Autores'] == 'Rick Riordan')
df[mascara]

Autores            Titulos  Preço
0  Rick Riordan  O Ladrão de Raios   41.2
2  Rick Riordan    Mar de Monstros   39.5

In [101]:
df.at[4,'Preço'] = 40.2

In [102]:
print(df)

            Autores                          Titulos  Preço
0      Rick Riordan                O Ladrão de Raios   41.2
1  J. R. R. Tolkien              A Sociedade do Anel   35.7
2      Rick Riordan                  Mar de Monstros   39.5
3  Machado de Assis  Memórias Postumas de Brás Cubas   40.5
4      Rick Riordan               A Maldição do Titã   40.2
